const buttonColors = ["green", "red", "yellow", "blue"]; // Array of possible button colors
let gamePattern = [];// Array to store the sequence generated by the game
let userClickedPattern = [];// Array to store the user's clicked pattern
let gameStarted = false;// Flag to track if the game has started or not
let level = 0; // Variable to store the current level


// Function to start the game when a key is pressed
function startGame() {
  if (!gameStarted) { // Check if the game has not started yet
    document.getElementById("level-title").textContent = "Level " + level;
    nextSequence();
    gameStarted = true;
  }
}
// Function to generate the next color sequence in the game
function nextSequence() {
  userClickedPattern = [];
  level++;
  document.getElementById("level-title").textContent = "Level " + level;

  const randomColor = buttonColors[Math.floor(Math.random() * 4)];
  gamePattern.push(randomColor);

  disableUserInput(); // Disable user input before showing the new color
  animateSequence();
}
// Function to disable user input by removing click event listeners
function disableUserInput() {
  const buttons = document.querySelectorAll(".btn");
  buttons.forEach((button) => {
    button.removeEventListener("click", handleButtonClick);
  });
}
// Function to enable user input by adding click event listeners
function enableUserInput() {
  const buttons = document.querySelectorAll(".btn");
  buttons.forEach((button) => {
    button.addEventListener("click", handleButtonClick);
  });
}
// Function to animate the color sequence
function animateSequence() {
  disableUserInput(); // Disable user input during animation

  const lastColorIndex = gamePattern.length - 1;
  const lastColor = gamePattern[lastColorIndex];

  setTimeout(function () {
    document.getElementById(lastColor).style.opacity = 0;
    setTimeout(function () {
      document.getElementById(lastColor).style.opacity = 1;
      playSound(lastColor);
      enableUserInput(); // Enable user input after showing the new color
    }, 100);
  }, 500);
}


function nextSequence() {
  userClickedPattern = [];
  level++;
  document.getElementById("level-title").textContent = "Level " + level;

  const randomColor = buttonColors[Math.floor(Math.random() * 4)];
  gamePattern.push(randomColor);

  animateSequence();
}
function enableUserInput() {
  const buttons = document.querySelectorAll(".btn");
  buttons.forEach((button) => {
    button.addEventListener("click", handleButtonClick);
  });
}


function handleButtonClick() {
  const userChosenColor = this.id;
  userClickedPattern.push(userChosenColor);

  animatePress(userChosenColor);
  playSound(userChosenColor);

  checkAnswer(userClickedPattern.length - 1);
}

function playSound(name) {
  const audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

function animatePress(currentColor) {
  document.getElementById(currentColor).classList.add("pressed");
  setTimeout(function () {
    document.getElementById(currentColor).classList.remove("pressed");
  }, 100);
}

function checkAnswer(currentLevel) {
  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) {
    if (userClickedPattern.length === gamePattern.length) {
      setTimeout(function () {
        nextSequence();
      }, 1000);
    }
  } else {
    playSound("wrong");
    document.body.classList.add("game-over");
    document.getElementById("level-title").textContent =
      "Game Over, Press Any Key to Restart";

    setTimeout(function () {
      document.body.classList.remove("game-over");
    }, 200);

    startOver();
  }
}

function startOver() {
  level = 0;
  gamePattern = [];
  gameStarted = false;
}

document.addEventListener("keypress", startGame);
document.getElementById("level-title").addEventListener("click", startGame);

const buttons = document.querySelectorAll(".btn");
buttons.forEach((button) => {
  button.addEventListener("click", handleButtonClick);
});
